### ISSUE TITLE
provides/requires tool metadata

### ISSUE THREAD

**Issue by schristley** [airr-community/airr-formats#17]
With the ongoing discussion #8 about mandatory fields, and the idea that a field could exist but might be null, made me think that if a tool "required" a particular column, just checking the existence of the column would be insufficient. One idea is to add metadata where a tool specifies what columns it "provides" and what columns it "requires" thus allowing a dependency graph to be built.

This could allow for some nice features in workflows:

* When running a tool on a file, it can stop if requirements are not met, instead of crashing or (worse) producing erroneous analysis.
* Given a file, what tools can be used on the file?
* Given a field, search for tools which would provide it.
* Given a set of fields, provide tool workflows that would provide them.

Maybe a bit of overkill if we are only talking about a handful of tools...

**Comment by scharch** [comment]
I can understand having that tool X added columns Y and Z in the metadata along with the version of X used and so on, but I don't see the value of including what inputs tool X needed. Isn't it moot by that point? Or, alternatively, doesn't this assume that we have an exhaustive catalog of tools and their requirements?

**Comment by schristley** [comment]
That's true. I guess I was thinking more like when the tool was being run, it could check if its required fields are available. That wouldn't need to be put in the metadata, so maybe just the provided fields.
