### ISSUE TITLE
`constant` in rearragements spec should be treated as alignment-derived

### ISSUE THREAD

**Issue by laserson** [airr-community/airr-formats#22]
Mike Shugay pointed out that `constant` should be treated as an alignment-derived field, which it often is.  We should probably rename to `constant_call` and add the associated fields (e.g., `_score`, `_cigar`).  Any thoughts?

**Comment by javh** [comment]
Agreed. Maybe `c_call`? If we want to future proof, we could also add fields for the leader. I think MiXCR is the only aligner that currently calls the leader explicitly. I don't know if it distinguishes it from the V call though.
