### ISSUE TITLE
Add explicit docs on numbering scheme

### ISSUE THREAD

**Issue by laserson** [airr-community/airr-formats#23]
It appears we forgot to make explicit the numbering scheme for coords.  IIRC, to minimize ambiguity of annotations, we decided to go with Python-style numbering (which is zero-indexed half-open intervals; or put another way, it's as if the indices are between the letters).

**Comment by javh** [comment]
Heh. You're too speedy @laserson... Reopening to comment. As I'm working through the CIGAR issues, I'm understanding why we went with `length` over `end` for positional information. I think `end` will still work fine, but I think we need to be explicit about whether `end` references the *alignment* or the *input*.  Any indels will make these values differ.

For example, given an alignment like this:
```
ATGGCCC
ATG--CC
```
Query end in the *alignment* is 7, but query end in the *input* sequence is 5. My inclination is to go with end position in the *input*, but then we need to make make encoding of indels in the CIGAR mandatory.

**Comment by schristley** [comment]
If we care, the [SAM spec](https://samtools.github.io/hts-specs/SAMv1.pdf) for the CIGAR string indicates one-indexed numbering.

**Comment by schristley** [comment]
@javh Yes, I agree, `I` and `D` should be mandatory in the CIGAR.

**Comment by schristley** [comment]
ah, but now I read that BAM uses zero-indexed numbering...

**Comment by javh** [comment]
We should check what the minimal standards group did.

**Comment by laserson** [comment]
After our poll, we decided to go with Python-style zero-indexed half-open slice notation.

**Comment by laserson** [comment]
This is currently reflected in the docs, so I will close.
