### ISSUE TITLE
CDR3 vs junction

### ISSUE THREAD

**Issue by javh** [airr-community/airr-formats#27]
Just wanted to see what opinions were on whether we should make the mandatory field the CDR3 (without conserved residues) or the junction (CDR3 plus flanking conserved residues). Minimal standards went with CDR3, but I don't think they are averse to changing it.

Also, I think the nucleotide sequence field should be denoted `nt` instead of `na`. Eg, `cdr3_nt` instead of `cdr3_na`. That seems more standard to me. 

Thoughts?

**Comment by matsen** [comment]
👍 for junction, and for `nt`.

**Comment by scharch** [comment]
+1 to what Erik said

**Comment by laserson** [comment]
+1 on junction and `nt`.

**Comment by schristley** [comment]
Sounds fine to me, just out of curiosity, why do you like have the junction residues included, is it useful for particular analysis?

**Comment by laserson** [comment]
I think it's fine either way.  Actually, if we have a data set with a billion rearrangements, it'll be an extra couple gigs of storage at least :P.  But I'm just personally more used to seeing the CDR3 sequence capped with the conserved residues.

**Comment by laserson** [comment]
Changed the `na` to `nt` in 421cec5

**Comment by nishmm** [comment]
+1 for Junction and nt. Junction is more scientific user friendly.

**Comment by laserson** [comment]
MinStd call:
Florian: people typically search/think of "cdr3". But CDR3 is a loss of info vs junction.
Christian: what if conserved residues are mutated? argument for junction
Nina: make sure docs include "CDR3" if we go with junction. (Florian seconds this)
Lindsay: more info is better, so go for the longer one

**Comment by bcorrie** [comment]
We have been looking at use cases a lot, and Florian's comment "people typically search/think of cdr3" holds with most of what we are hearing... With that said, when searching one typically searches for a substring of the entire CDR3 so having the CDR3 as a substring of Junction is probably fine. My main concern would be if people "think" CDR3 do we confuse them if we talk "Junction". My ignorance here as a non-biologist, but if we map Minimal Standards to Formats through to a tool or user interface in a fairly literal form do we run into problems... If a user interface says "Search Junction" would it be clear to the average user that this is also how they would search for a CDR3 sequence? 

Brian

**Comment by laserson** [comment]
Yeah, I think the consensus on the call ultimately was that we should report "junction" as defined by IMGT, but make sure the docs are crystal clear that this refers to "CDR3" as would be used colloquially.
