### ISSUE TITLE
Two sample_type in Minimal Standard YAML files...

### ISSUE THREAD

**Issue by bcorrie** [airr-community/airr-formats#32]
Are we expecting the minimal standard field identifiers in the YAML files to be unique across the minimal standard fields.

There are currently two sample_type fields, one in sample.yaml and one in cell_processing.yaml.

Is this an issue?

Brian

**Comment by schristley** [comment]
Technically yes as sample and cell_processing are distinct entities so they can have their own local attribute. Typically those attributes are foreign keys, e.g. both sample and cell_processing could have a subject_id. In this case however, sample_type in cell_processing looks to be an ambiguous field. The description says "single cell or bulk?" which doesn't sound the same as sample_type.

**Comment by schristley** [comment]
The "minimal-standards" branch is old. Now with an airr-standards repo, the spec will reside there.
