### ISSUE TITLE
Convert yaml spec to swagger compatible schema definition

### ISSUE THREAD

**Issue by schristley** [airr-community/airr-formats#37]
Because we don't have any restrictions on the format of the yaml spec, it might be a good idea to convert it to a swagger compatible [schema object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#schemaObject) definition. Then it can be referenced directly by a swagger API spec. This would be useful for the common repository WG which is considering a REST API.

**Comment by laserson** [comment]
Is it a lot of work to put together a PR for us to look at?  Could help in evaluating whether we want to go in this direction.

**Comment by bcorrie** [comment]
Hi All,

I think this would be extremely valuable. For the iReceptor API I am currently referring to the externally defined YAML files that Scott has defined in:

https://raw.githubusercontent.com/airr-community/airr-standards/master/specs/definitions.yaml

These are already Swagger compliant definitions, and by using the AIRR standards files in the iReceptor Swagger definition our API automatically uses all of the AIRR Minimal Standard fields (and the AIRR format tag names for those fields). 

If you look at this document here:

https://github.com/sfu-ireceptor/api/blob/AIRR-compliance/iReceptor_Data_Service_API_V2.yaml

you will see the references to the external YAML files (line 38). 

This makes it almost "trivial" for our API to communicate using AIRR compliant fields. Our v2 API, which we are targeting to have ready for the December meeting, should be passing around AIRR compliant data between the iReceptor repositories and the iReceptor Gateway...

I would strongly support this and would be happy to contribute to the effort!!!

**Comment by schristley** [comment]
This is in airr-standards repo.
