### ISSUE TITLE
Merge airr-formats and airr-standards

### ISSUE THREAD

**Issue by laserson** [airr-community/airr-formats#44]
And publish a single RTFD page at docs.airr-community.org or something like that.

**Comment by schristley** [comment]
We should merge all the branches before moving anything, there is significant work on the changeo-integration branch for example.

**Comment by schristley** [comment]
@laserson Did we get consensus on this? I'd like this to be done sooner rather than later, we are talking about a airr-standards repo freeze and release next week, so groups like iReceptor can have a stable release for API work for Dec. AIRR meeting.

**Comment by javh** [comment]
Would it make sense to version tag the airr-standards repo before merging then? (Ie, merge after an official version number.)

**Comment by schristley** [comment]
Yes, maybe, https://github.com/airr-community/airr-standards/issues/22

There is a call next week with Christian and Brian about doing a freeze, if you want to be involved, I can send the call info.

**Comment by laserson** [comment]
Seems people are generally in agreement.

**Comment by schristley** [comment]
I will put a version of the rearrangement annotations into airr-standards this week for the release, but the software release and changes to handle the different spec format will come later.

**Comment by laserson** [comment]
Done-ish.
