### ISSUE TITLE
Alignments table should have a key into the rearrangements

### ISSUE THREAD

**Issue by laserson** [airr-community/airr-formats#47]
There is a one-to-many relationship btwn rearrangement and alignments, or at least to the reads themselves. Where do we store this information?  Is it just destroyed?

**Comment by javh** [comment]
It should be the `id` field, yes? Which maps to `sequence_id` in the alignments file.

**Comment by laserson** [comment]
This is also addressed in 4610d549f287d2f96fee71f4689de608195811ba
