### ISSUE TITLE
Genbank structured comments

### ISSUE THREAD

**Issue by laserson** [airr-community/airr-formats#51]
From @javh:

>We should also discuss whether we can/should design these fields with the intention of using them in GenBank structured comments. This is one of the things that came up when working through the AIRR minimal information GenBank submission process. It's something we can add to the submissions, if we want, but we need to have a clearly defined vocabulary to give NCBI so that they can parse it and tag the data as AIRR.

**Comment by javh** [comment]
[GenBank structured comments](https://www.ncbi.nlm.nih.gov/genbank/structuredcomment).

Here's an example comment (`.cmt`) file to generate GenBank structured comments:

```
StructuredCommentPrefix    AIRR
library_source             mRNA
platform                   Illumina MiSeq
read_length                325+275
software_versions          pRESTO:0.5.4,Change-O:0.3.8,IMGT/HighV-QUEST:1.5.5
paired_end_assembly        de novo and reference guided
quality_thresholds         Q>20
primer_match_cutoffs       5'RACE:0.5,C_region:0.2
consensus_method           UMI group majority rule weighted by quality score
StructuredCommentSuffix    AIRR
```

I was thinking about this more in the context of the meta-data file than the rearrangements file.

**Comment by laserson** [comment]
@javh should we transfer this to the other repo?

**Comment by javh** [comment]
Yeah, I think so. At least as a discussion point for long term goals.

**Comment by laserson** [comment]
Marking this as closed here.  Discussion to continue at the airr-standards repo.
